#!/bin/bash

#put your ascii-art here



#for example
#echo -e "                                                               "
#echo -e "${c2}                            ██                            "
#echo -e "${c2}                           ████                           "
#echo -e "${c2}                          ██████                          "
#echo -e "${c2}                         ████████                         "
#echo -e "${c2}                        ██████████                        "
#echo -e "${c2}                       ████████████                       "
#echo -e "${c2}                      ██████████████                      "
#echo -e "${c2}                     ████████████████                     "
#echo -e "${c2}                    ██████████████████                    "
#echo -e "${c2}                   ████████████████████                   "
#echo -e "${c2}                  ██████████████████████                  "
#echo -e "${c2}                 ██████████     █████████                 "
#echo -e "${c2}                ██████████       █████████                "
#echo -e "${c2}               ██████████         █████████               "
#echo -e "${c2}              ███████████         ██████████              "
#echo -e "${c2}             ████████████         ███████████             "
#echo -e "${c2}            ████████                  ████████            "
#echo -e "${c2}           ████                            ████           "
#echo -e "${c2}          ██                                  ██          "


# btw I'm providing some ascii art for the distros i use so ..

# Arch Linux!
#source ~/ftch/.ascii/arch

# manjaro-linux
#source ~/ftch/.ascii/manjaro